name: Action CI

on:
  push:
    tags:
      - "*"

concurrency: new-tag
jobs:
  release:
    name: GitHub Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: compute-version
        name: Compute version
        uses: ./
      - name: Release
        if: ${{ steps.compute-version.outputs.should-release == 'true' }}
        uses: EasyDesk/action-semver-release@v1
        with:
          version: ${{ steps.compute-version.outputs.version }}
          prerelease: ${{ steps.compute-version.outputs.is-github-prerelease }}